store request body after logging
vercel/micro-dev pull request #88
Opened 2018-07-23 05:14 UTC by maxbeatty

This simple API works with `micro` but not `micro-dev`. I believe it has to do with how the logger is reading the body of the request. Without this change, the request hangs using `micro-dev`. By assigning the parsed JSON to the request, `express-graphql` can [use it later](https://github.com/graphql/express-graphql/blob/41e26f803f4bf6888a4dedf9af99153892d13eb4/src/parseBody.js#L28).

I understand this is a bit hacky and aimed at express middleware that doesn't take advantage of [multiple calls to `json`](https://github.com/zeit/micro/blob/c09975700ab721bd5b556d5467e9a6a929875470/lib/index.js#L112-L114). Is there another way to get `micro` and `micro-dev` behaving consistently?

```js
const graphqlHTTP = require("express-graphql");
const { buildSchema } = require("graphql");
const jwtAuth = require("micro-jwt-jwks-rsa-auth");

const schema = buildSchema(`
  type Query {
    random: Float!
  }
`);

const root = {
  random: () => Math.random()
};

const checkJwt = jwtAuth({
  jwksRsaConfig: {
    jwksUri: `https://your-project.auth0.com/.well-known/jwks.json`
  }
});

module.exports = checkJwt(graphqlHTTP({
  schema,
  rootValue: root
}));
```

2018-10-02 22:58 UTC, maxbeatty commented
@Leo thoughts on this?

2018-12-03 12:16 UTC, timneutkens requested changes
You could do something like this I guess:

```js
function reqBodyMiddleware(fn) => {
  return (req, res) => {
    const body = await json(req)
    req.body = body
    return fn(req, res)
  }
}
```

2018-12-03 17:26 UTC, maxbeatty commented
Ya that probably is how I worked around it (or at least debugged it). Was bummed to add code to make dev tool work when not needed in prod

2018-12-03 18:37 UTC, timneutkens commented
But how does this differ from `micro`?

2018-12-03 19:04 UTC, maxbeatty commented
Doing this a bit from memory so apologies if not 100% accurate 😇 `micro-dev` logger drains the incoming request so when it comes time for `express-graphql` to read, it’s empty and thus hangs. `micro` does not read the request body internally so the incoming request stays in tact. By assigning the already-read JSON to `req.body`, non-micro middleware like express can look at that first and happily continue. This makes the same express code work the same when using either micro.

2018-12-03 19:12 UTC, timneutkens commented
Alright, I see. We can't take this fix though since it adds even more unexpected behavior to micro-dev vs micro

2018-12-03 19:16 UTC, maxbeatty commented
Ya I get it’s wonky 🙇‍♂️

Thankfully [better micro GraphQL servers](
https://www.apollographql.com/docs/apollo-server/servers/micro.html) have emerged 🙌

2018-12-03 19:16 UTC, closed without merging

2018-12-03 19:19 UTC, timneutkens commented
💯